CREATE TABLE learning_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    learning_month DATE NOT NULL,
    learning_hours INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_learning_data_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_learning_data_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT uq_learning_data
        UNIQUE (
            user_id,
            category_id,
            item_name,
            learning_month
        )
);
